# This file was generated by GoReleaser. DO NOT EDIT.
cask "acid" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-darwin-amd64.tar.gz"
      sha256 "1c566c86181f36d3b50c562d5e53cf89bb23adaa1972f3ce91ce89cabd27e651"
    end
    on_arm do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-darwin-arm64.tar.gz"
      sha256 "1d5419174d49f80a17224ef56c1ceb6e9a475ef296a1cc22399db364a2694eec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-linux-amd64.tar.gz"
      sha256 "b081833f4161a21293ed3a40d011351a3f3268560ef2de4a843905fb164716cf"
    end
    on_arm do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-linux-arm64.tar.gz"
      sha256 "925d7f812cb31d2798e7c523134c283bdeae35ca7bdb73f603615021fd7b6619"
    end
  end

  name "acid"
  desc "Terminal tool for visualizing and testing SQL transaction sequences."
  homepage "https://github.com/rusinikita/acid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acid"

  # No zap stanza required

end
