# This file was generated by GoReleaser. DO NOT EDIT.
cask "acid" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-darwin-amd64.tar.gz"
      sha256 "45886eee2b14cad145ab70e927eb26381c5c1687c7eb31fb7409eccbae301d19"
    end
    on_arm do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-darwin-arm64.tar.gz"
      sha256 "7a63beee02ff99df87c2bc281083568b4592454511c45ec07dd98db2144478af"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-linux-amd64.tar.gz"
      sha256 "4bdf01a63e2bb4c97be0b8b11eb3293059ea8b01ecedaf20af9b9b7a3f03baa3"
    end
    on_arm do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-linux-arm64.tar.gz"
      sha256 "029e67e031cab6d9403ae97abd5ec31b3b328f3ab5fda8f7a874e191b236dd3a"
    end
  end

  name "acid"
  desc "Terminal tool for visualizing and testing SQL transaction sequences."
  homepage "https://github.com/rusinikita/acid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acid"

  # No zap stanza required

end
