# This file was generated by GoReleaser. DO NOT EDIT.
cask "acid" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-darwin-amd64.tar.gz"
      sha256 "1840d04d5f558cf74d99555aaf33cd93182483e180edb28837ba1be8a226e4fe"
    end
    on_arm do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-darwin-arm64.tar.gz"
      sha256 "d8100c89df789d73013cb5094f73ba061d0fdf83651b94407a67604e116cd9ca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-linux-amd64.tar.gz"
      sha256 "6b0a92196f0721070db4c472f2d81f531a3e3bb0047b9c059c6a5cfb4079c9bb"
    end
    on_arm do
      url "https://github.com/rusinikita/acid/releases/download/v#{version}/acid-#{version}-linux-arm64.tar.gz"
      sha256 "bc160bb340971a94c3c6ac8f8831a2a15950dec686d0d99dc56a51e4a049adf8"
    end
  end

  name "acid"
  desc "Terminal tool for visualizing and testing SQL transaction sequences."
  homepage "https://github.com/rusinikita/acid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "acid"

  # No zap stanza required

end
