# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changes < Formula
  desc "Helps to automate code review and enforce team agreements."
  homepage "https://github.com/rusinikita/changes"
  version "1.0.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rusinikita/changes/releases/download/v1.0.0/changes-1.0.0-darwin-arm64.tar.gz"
      sha256 "0a571f279b58c5c66ceee2dbcd03fb601925075b91bc9a3a8b014d28da08e96b"

      def install
        bin.install "changes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rusinikita/changes/releases/download/v1.0.0/changes-1.0.0-darwin-amd64.tar.gz"
      sha256 "0d1f4b382397a33e39205173844e2eaaa76cb93ac4b7f13f69f81ba46a78d194"

      def install
        bin.install "changes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusinikita/changes/releases/download/v1.0.0/changes-1.0.0-linux-arm64.tar.gz"
      sha256 "0242c29d3c5f8b4d40c16db0db8975077e0119a3bc6f31f08d8dafe65a599f75"

      def install
        bin.install "changes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rusinikita/changes/releases/download/v1.0.0/changes-1.0.0-linux-amd64.tar.gz"
      sha256 "e039b434250feb3881f012afdc91e6f117db2a3c18a12c71b515019572876393"

      def install
        bin.install "changes"
      end
    end
  end

  test do
    system "#{bin}/changes version"
  end
end
