# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changes < Formula
  desc "Helps to automate code review and enforce team agreements."
  homepage "https://github.com/rusinikita/changes"
  version "0.3.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rusinikita/changes/releases/download/v0.3.0/changes_Darwin_x86_64.tar.gz"
      sha256 "e5e6137f55d96e8782050f22478b2b65c8797600469be3efc5907258f3339215"

      def install
        bin.install "changes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rusinikita/changes/releases/download/v0.3.0/changes_Darwin_arm64.tar.gz"
      sha256 "a28a8bc7a93cc5289414c997799bddc45b5e7bbc76ae4206ad384a5e593417cc"

      def install
        bin.install "changes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rusinikita/changes/releases/download/v0.3.0/changes_Linux_x86_64.tar.gz"
      sha256 "d62e0321c2d1ce6e62a415e4d584d190f63b247287baa361b50960df7127d40f"

      def install
        bin.install "changes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusinikita/changes/releases/download/v0.3.0/changes_Linux_arm64.tar.gz"
      sha256 "59ef924f95b289469651a08fee6660bdb487fc49761101e99a883113dde96424"

      def install
        bin.install "changes"
      end
    end
  end

  test do
    system "#{bin}/changes version"
  end
end
