# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devex < Formula
  desc "Git codebase visualization. Development experience insights."
  homepage "https://github.com/rusinikita/devex"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rusinikita/devex/releases/download/v0.1.3/devex_Darwin_arm64.tar.gz"
      sha256 "2ec28923590f5f225152d271a0461baa1691c6e6bec3a7e99a346d612ae0bd9c"

      def install
        bin.install "devex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rusinikita/devex/releases/download/v0.1.3/devex_Darwin_x86_64.tar.gz"
      sha256 "36e5c355456894cacd56597c81e5b226f8abc61fde64b5a2470065bd7b64a51e"

      def install
        bin.install "devex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusinikita/devex/releases/download/v0.1.3/devex_Linux_arm64.tar.gz"
      sha256 "3c526265e84889ae3a0010ad4cd6322c6df7efd66a19949059972d1c9c05efa1"

      def install
        bin.install "devex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rusinikita/devex/releases/download/v0.1.3/devex_Linux_x86_64.tar.gz"
      sha256 "fe6fd111bf6ac9f36c29b6b1f51a8dbeec23c460cf339dbc16a79f96fe86df6b"

      def install
        bin.install "devex"
      end
    end
  end

  test do
    system "#{bin}/golangci-lint version"
  end
end
