# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SystemDesignTrainer < Formula
  desc "Interactive Go-based training platform for system design and high-load engineering challenges"
  homepage "https://github.com/rusinikita/system-design-trainer"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rusinikita/system-design-trainer/releases/download/v0.4.0/system-design-trainer_Darwin_x86_64.tar.gz"
      sha256 "5ac38591b53c635e716528418838d99864b3869404cf4d484fd75794c3d85593"

      def install
        bin.install "sdt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rusinikita/system-design-trainer/releases/download/v0.4.0/system-design-trainer_Darwin_arm64.tar.gz"
      sha256 "1b23b95b399ab16830a289607064b6d8819d66cb9d0f1d3faf62eb04e1eb269b"

      def install
        bin.install "sdt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusinikita/system-design-trainer/releases/download/v0.4.0/system-design-trainer_Linux_x86_64.tar.gz"
      sha256 "ad032ccc2f2b613f72a5f9ba576c3784f863d7a18fc65c2a0f2ca49b97953c19"
      def install
        bin.install "sdt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusinikita/system-design-trainer/releases/download/v0.4.0/system-design-trainer_Linux_arm64.tar.gz"
      sha256 "fb00cdeaf9f1ec3cc3875153ab8b1f7dc50eed12ba26bf2f99435660cd16feb1"
      def install
        bin.install "sdt"
      end
    end
  end

  test do
    system "#{bin}/sdt", "--version"
  end
end
