# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SystemDesignTrainer < Formula
  desc "Interactive Go-based training platform for system design and high-load engineering challenges"
  homepage "https://github.com/rusinikita/system-design-trainer"
  version "0.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rusinikita/system-design-trainer/releases/download/v0.14.0/system-design-trainer-0.14.0-darwin-amd64.tar.gz"
      sha256 "dbc860bcf2880ff8fe714c5bf54163ca01098e7a250cc7316d8e99e1eb94680e"

      define_method(:install) do
        bin.install "sdt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rusinikita/system-design-trainer/releases/download/v0.14.0/system-design-trainer-0.14.0-darwin-arm64.tar.gz"
      sha256 "73e3b60f7e4baa6c99333c8c364d8971b327c8f9f3d41905c8133985010e1e31"

      define_method(:install) do
        bin.install "sdt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusinikita/system-design-trainer/releases/download/v0.14.0/system-design-trainer-0.14.0-linux-amd64.tar.gz"
      sha256 "4189c410660c69193bf2397cdb4e50425235f63751aab3f367cd5dec5c583c97"
      define_method(:install) do
        bin.install "sdt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rusinikita/system-design-trainer/releases/download/v0.14.0/system-design-trainer-0.14.0-linux-arm64.tar.gz"
      sha256 "097a829a5c7e22f611075c42e88c30a5fc270b12092024206d9209eda227c2bb"
      define_method(:install) do
        bin.install "sdt"
      end
    end
  end

  test do
    system "#{bin}/sdt", "--version"
  end
end
